### ISSUE TITLE
How many shots are used for the CoT and vanilla LM baselines?

### ISSUE THREAD

**Issue by fc2869** [OceannTwT/era-cot#5]
This is a very interesting paper and thanks for making the code publicly available. I am wondering about some details of the baseline in Table 1: How many ICL shots are used for the CoT and vanilla LM baselines?

**Comment by OceannTwT** [comment]
cot for @5，vanilla LM for @0

**Comment by fc2869** [comment]
Thank you for the prompt response. Much appreciated!
